### ISSUE TITLE
Artyom with express

### ISSUE THREAD

**Issue by 4bull** [sdkcarlos/artyom.js#42]
Hi, I'm trying to use artyom in a express nods app. I added with the following command (inside the project folders) 

`npm install artyom.js`

And I see it in node_modules. In app.js I add the following lines:

```
var artyom = require('artyom.js/build/artyom.js');
const jarvis = new Artyom();
```

but when I start the app I got the following error:

```
const jarvis = new Artyom();
ReferenceError: Artyom is not defined
```

Any idea why? Thanks
4b

**Comment by sdkcarlos** [comment]
Have you tried just `require("artyom.js")` ? It should work out of the box requiring only the name of the module.

**Comment by 4bull** [comment]
of course but no chance, doesn't work with only artyom.js, is for that I have tried with full path.
Others module works out of the box.

Any others idea?

**Comment by sdkcarlos** [comment]
Ah, the error is not the module, check the uppercase:

```javascript
var Artyom = require('artyom.js');

const jarvis = new Artyom();
```

**Comment by 4bull** [comment]
yes, I found this typo error me too. Thanks
but it doesn't work anyway.... I got 

```
const jarvis = new Artyom();
               ^

TypeError: Artyom is not a constructor
```

**Comment by mamihelj09** [comment]
Has anyone solved this?

**Comment by webleyson** [comment]
Are you running this in the browser?

**Comment by alineo** [comment]
Hello, I have the same issue :/
I want to use Artyom in a bot for Discord (made with node.js)

[link imgur](https://i.imgur.com/t3wg1Rf.png)
`const Artyom = require("artyom.js");
const artyom = new Artyom();`

> const artyom = new Artyom();
TypeError: Artyom is not a constructor



Does someone know what it is or what to do ?
Thanks

**Comment by DigitalFlux** [comment]
I ran into this issue recently in working with this after doing npm install on nodejs, and found that changing:
`exports.default = Artyom;`
to:
`exports.Artyom = Artyom;`
At the end of build/artyom.js allowed me to do the following:
`var Artyom = require('./node_modules/artyom.js/build/artyom.js').Artyom;
this.voice = new Artyom();`

_this_ being a class that assigns the new Artyom object to its voice member. I'm able to start it up, and now I'm just going through trying to get it to recognize any voice inputs (which may be a different issue than something inside Artyom, since I'm experimenting with node inside Electron right now).

If that issue has to do with Artyom, I'll update..

**Comment by rodrigooler** [comment]
@DigitalFlux 

```js
I ran into this issue recently in working with this after doing npm install on nodejs, and found that changing:
exports.default = Artyom;
to:
exports.Artyom = Artyom;
At the end of build/artyom.js allowed me to do the following:
var Artyom = require('./node_modules/artyom.js/build/artyom.js').Artyom; this.voice = new Artyom();

this being a class that assigns the new Artyom object to its voice member. I'm able to start it up, and now I'm just going through trying to get it to recognize any voice inputs (which may be a different issue than something inside Artyom, since I'm experimenting with node inside Electron right now).

If that issue has to do with Artyom, I'll update..
```
In case I just managed to make it work because of your comment above to adjust the export unfortunately it is not working in the current version. I was able to make parts work on electron but I need to solve the window problem. I'll put the solution here if I can.

**Comment by amreen-rajmohmad** [comment]
Same here. I also tried the solution mentioned above about changing default export.
following is the error i get : 
`(base) LT6564:node-server-tutorial amreen.rajmohmad$ node server.js 
/Users/amreen.rajmohmad/Documents/node-server-tutorial/node_modules/artyom.js/build/artyom.js:59
        if (window.hasOwnProperty('speechSynthesis')) {
            ^

ReferenceError: window is not defined
    at new Artyom (/Users/amreen.rajmohmad/Documents/node-server-tutorial/node_modules/artyom.js/build/artyom.js:59:13)
    at Object.<anonymous> (/Users/amreen.rajmohmad/Documents/node-server-tutorial/server.js:11:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)`

**Comment by amreen-rajmohmad** [comment]
Okay, So how i resolved this is : 

`const Artyom = require('artyom.js').default;
`
since I was facing a windows error as I mentioned in my previous comment 
I saw there was already a PR addressing it. 

https://github.com/sdkcarlos/artyom.js/pull/98/files

I replaced my Artyom.js file with these updated changes.

Then to make sure that node_modules use this changes : run following command from your package. it will create patches folder. 

`npx patch-package <package name>
`
and add the following flag in your package.json so that on npm install this patch is applied again.

`"postinstall": "npx patch-package" 
`

https://stackoverflow.com/questions/13300137/how-to-edit-a-node-module-installed-via-npm
